name: ArrivaBus hidegtárolás_2

on:
  schedule:
    - cron: "2 0 * * *"
      timezone: "Europe/Budapest"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: hidegtarolas-main
  cancel-in-progress: false

jobs:
  teszt:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v5

      - name: Python beállítása
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Csomagok telepítése
        run: pip install -r requirements.txt

      - name: Budapest dátum meghatározása
        id: datum
        run: |
          echo "datum=$(TZ=Europe/Budapest date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: GTFS cache betöltése
        uses: actions/cache@v4
        with:
          path: gtfs_cache
          key: gtfs-cache-${{ steps.datum.outputs.datum }}

      - name: Program futtatása
        env:
          BKK_API_KEY: ${{ secrets.BKK_API_KEY }}
        run: python main.py

      - name: Napi adatok mentése
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add napi_adatok.json index.html

          if git diff --cached --quiet; then
            echo "Nincs új mentendő adat."
          else
            git commit -m "Napi adatok és HTML export frissítése"
            git push
          fi
